import { ChartType } from "../types/chart.type";

export const data: ChartType[] = [
  {
    name: "Bitcoin",
    dataGraph: [
      { value: 10, dataPointText: "10" },
      { value: 20, dataPointText: "20" },
      { value: 30, dataPointText: "30" },
      { value: 40, dataPointText: "40" },
      { value: 50, dataPointText: "50" },
      { value: 60, dataPointText: "60" },
      { value: 70, dataPointText: "70" },
      { value: 80, dataPointText: "80" },
      { value: 90, dataPointText: "90" },
      { value: 40, dataPointText: "40" },
    ],
  },
  {
    name: "Ethereum",
    dataGraph: [
      { value: 20, dataPointText: "20" },
      { value: 30, dataPointText: "30" },
      { value: 40, dataPointText: "40" },
      { value: 50, dataPointText: "50" },
      { value: 60, dataPointText: "60" },
      { value: 70, dataPointText: "70" },
      { value: 80, dataPointText: "80" },
      { value: 90, dataPointText: "90" },
      { value: 40, dataPointText: "40" },
    ],
  },
  {
    name: "Tesla",
    dataGraph: [
      { value: 30, dataPointText: "30" },
      { value: 40, dataPointText: "40" },
      { value: 50, dataPointText: "50" },
      { value: 60, dataPointText: "60" },
      { value: 70, dataPointText: "70" },
      { value: 80, dataPointText: "80" },
      { value: 90, dataPointText: "90" },
      { value: 100, dataPointText: "100" },
      { value: 40, dataPointText: "40" },
    ],
  },
  {
    name: "Amazon",
    dataGraph: [
      { value: 40, dataPointText: "40" },
      { value: 50, dataPointText: "50" },
      { value: 60, dataPointText: "60" },
      { value: 70, dataPointText: "70" },
      { value: 80, dataPointText: "80" },
      { value: 90, dataPointText: "90" },
      { value: 100, dataPointText: "100" },
      { value: 110, dataPointText: "110" },
    ],
  },
  {
    name: "Microsoft",
    dataGraph: [
      { value: 50, dataPointText: "50" },
      { value: 60, dataPointText: "60" },
      { value: 70, dataPointText: "70" },
      { value: 80, dataPointText: "80" },
      { value: 90, dataPointText: "90" },
      { value: 100, dataPointText: "100" },
      { value: 110, dataPointText: "110" },
      { value: 120, dataPointText: "120" },
    ],
  },
  {
    name: "Google",
    dataGraph: [
      { value: 60, dataPointText: "60" },
      { value: 70, dataPointText: "70" },
      { value: 80, dataPointText: "80" },
      { value: 90, dataPointText: "90" },
      { value: 100, dataPointText: "100" },
      { value: 110, dataPointText: "110" },
      { value: 120, dataPointText: "120" },
      { value: 130, dataPointText: "130" },
    ],
  },
];
